10 08 08 //the magic number for this format file
# Constant logarithmic spacing within the selected energy range.
# E_min=1 eV  E_max=1000 keV
# R=300; nominal delta(ln E)=1/R.
# Format: upper_limit_Ryd  resolving_power
0.0734986450157  10
73498.6450157  200
0  33.333333
